sudo: required

services:
  - docker

install:
  - pip install --upgrade setuptools
  - git clone https://github.com/ansible/ansible-container.git
  - cd ansible-container && python ./setup.py install

script:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      echo "Building apps for deployment";
      export APPS=`ls | grep '\-ansibleapp'`
    ; else
      echo "Building apps for testing";
      export APPS=`git diff --name-only origin/master | awk -F '/' '{print $1}' | grep '\-ansibleapp'`
    ; fi
  - echo "ansibleapps to be built: $APPS"
  - for app in $APPS ; do
    ( cd $app ; ansible-container build ) ; done
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      for app in $APPS ; do
        (cd $app ; ansible-container push --tag latest --push-to docker.io/ansibleapp --username $DOCKER_USERNAME --password $DOCKER_PASSWORD)
      ; done
    ; fi
  - docker images
