sudo: required

services:
  - docker

install:
  - pip install --upgrade setuptools
  - git clone https://github.com/ansible/ansible-container.git
  - cd ansible-container && python ./setup.py install

script:
  - echo "Building ansibleapp-base"
  - docker build -t docker.io/ansibleapp/ansibleapp-base:latest ansibleapp-base
  - export APPS=`ls | grep '\-ansibleapp'`
  - echo "ansibleapps detected: $APPS"
  - echo "Building ansible-container based apps"
  - for app in $APPS ; do
      (cd $app ; [[ -s "ansible/container.yml" ]] || continue ;
      ansible-container build)
    done
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      for app in $APPS ; do
        (cd $app ; ansible-container push --tag latest --push-to docker.io/ansibleapp --username $DOCKER_USERNAME --password $DOCKER_PASSWORD)
      ; done
    ; fi
  - docker images
