version: "1"
services:
  db:
    image: centos:7
    command: ['/usr/bin/mysqld_safe']
    
  wordpress:
    image: centos:7
    links:
      - db
    command: bash -c "bash /tmp/a.sh ; usr/sbin/apachectl -D FOREGROUND"
    
